name: Auto Deployment
on:
  push:
    branches:
      - develop
      - release/*
  workflow_dispatch:
      inputs:
        run_number:
          description: 'Overwrite run number'
          required: false
          default: ''
jobs:
  calculate-environment-build-number:
    runs-on: [ubuntu-latest]
    outputs:
      build_number: ${{ steps.calculate-build-number.outputs.build_number }}
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: Printing traceability
        run: |
          echo "Running in ${{ github.repository }}"
      - name: Set Environment
        id: set-environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/release/'* ]]; then
            environment=test
          else
            environment=dev
          fi
          echo "environment=$environment" >> $GITHUB_OUTPUT
      - name: Print environment
        run: |
          echo "Environment: ${{ steps.set-environment.outputs.environment }}"
      - name: Calculate Build Number
        id: calculate-build-number
        run: |
          code_version=${{ vars.CODE_VERSION }}
          run_number=${{ github.event.inputs.run_number != '' && github.event.inputs.run_number || github.run_number }}
          build_number=$(echo $code_version | sed "s/x/$run_number/")
          if [[ ${{ steps.set-environment.outputs.environment }} == 'test' ]]; then
            build_number="t$build_number"
          fi
          echo "build_number=$build_number" >> $GITHUB_OUTPUT
      - name: Print build number
        run: |
          echo "Build Number: ${{ steps.calculate-build-number.outputs.build_number }}"
  build-upload-app:
    needs: calculate-environment-build-number
    uses: PepeMtzCampos/gha-env/.github/workflows/build-upload-react.yml@1fa3887c06d971039b52815ff07b5c6a55920a55
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      build_number: ${{ needs.calculate-environment-build-number.outputs.build_number }}
      environment: ${{ needs.calculate-environment-build-number.outputs.environment }}
      folder_suffix: ${{ vars.FOLDER_SUFFIX }}
  deploy-app:
    needs:
      - calculate-environment-build-number
      - build-upload-app
    uses: PepeMtzCampos/gha-env/.github/workflows/deploy-app.yml@1fa3887c06d971039b52815ff07b5c6a55920a55
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      build_number: ${{ needs.calculate-environment-build-number.outputs.build_number }}
      environment: ${{ needs.calculate-environment-build-number.outputs.environment }}
      folder_suffix: ${{ vars.FOLDER_SUFFIX }}